config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
    SPECIES = ["cat", "dog"]

    validates :name, :address, :species, :found_on, presence: true
    validates :species, inclusion: { in: SPECIES, message: "We only work with cats and dogs." }

    def found_days_ago
        (Date.today - self.found_on).to_i
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    before_action :set_pet, only: [ :show, :edit, :update, :destroy ]

    def index
        @pets = Pet.all
    end

    def show; end

    def new
        @pet = Pet.new
    end

    def create
        @pet = Pet.new(pet_params)

        if @pet.save
            redirect_to pet_path(@pet)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit; end

    def update
        @pet.update(pet_params)

        if @pet.save
            redirect_to pet_path(@pet)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @pet.destroy

        redirect_to pets_path, status: :see_other
    end

    private

    def set_pet
        @pet = Pet.find(params[:id])
    end

    def pet_params
        params.require(:pet).permit(:name, :address, :species, :found_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1524</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container pt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :species, as: :select, collection: Pet::SPECIES %>
    <%= f.input :found_on %>
    <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<%= render "form"%>

app/views/pets/index.html.erb
<h1>All Pets</h1>

<ul>
    <% @pets.each do |pet| %>
        <li><%= link_to pet.name, pet_path(pet) %></li>
    <% end %>
</ul>

<br>
<%= link_to "Report new pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>Report Missing Pet</h1>
<%= render "form" %>

app/views/pets/show.html.erb
<h1>Details about <%= @pet.name %> - <%= @pet.species %></h1>
<p>Found at <%= @pet.address %>, <%= @pet.found_days_ago %> days ago</p>

<%= link_to "Edit pet", edit_pet_path(@pet) %>
<br>
<%= link_to "Delete pet", pet_path(@pet),
    data:  { turbo_method: :delete, turbo_confirm: "Are you sure?" }
%>
<br>
<%= link_to "Back to all", pets_path %>